#!/usr/bin/env python3
"""
build.py -- regenerate the data files in this repository.
===============================================================================

WHAT IS THIS?
-------------
Every file in csv/, json/, db/, schemas/ and docs/topics/ is produced by this
script. Nothing is hand-written and nothing is hand-edited -- if a value is
wrong, the fix goes in a generator, not in the file.

QUICK START
-----------
    pyenv local realistic-test-data                 # activate the project's Python
    pip install -r requirements.txt        # once
    python build.py --all                  # rebuild everything

COMMON TASKS
------------
    python build.py --list
        Show the topics and entities that exist.

    python build.py --topic clinical
        Rebuild one topic, every format.

    python build.py --topic clinical --format csv,json
        Rebuild one topic, only the formats named.

    python build.py --topic clinical --scale 10
        Ten times as many rows. Use this when you need a big file for a load
        test; the relationships between tables hold at any scale.

WILL THIS CHANGE MY FILES?
--------------------------
Only if a generator changed. The random number generators are seeded from a
fixed master seed (generators/common/seeds.py), so running this twice on two
different machines produces byte-identical output. That is deliberate: it
means `git status` after a rebuild shows exactly what your change affected,
and nothing else.
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(REPO_ROOT))

from generators.common.schema import Topic  # noqa: E402
from generators.common.writers import (  # noqa: E402
    write_csv,
    write_json,
    write_ndjson,
    write_schema,
    write_schema_sql,
    write_sql_dump,
    write_sqlite,
)
from generators.renderers.erd import (  # noqa: E402
    graphviz_available,
    render_erd,
)
from generators.renderers.docs import (  # noqa: E402
    write_format_indexes,
    write_topic_docs,
)
from generators.topics import (  # noqa: E402
    automobile,
    clinical,
    education,
    finance,
    supermarket,
)

# ---------------------------------------------------------------------------
# The topic registry
# ---------------------------------------------------------------------------
# Adding a topic means writing generators/topics/<name>.py and adding one line
# here. Nothing else in the build needs to know about it.
#
# Each entry maps the topic name to (Topic object, generate function).

TOPICS: dict[str, tuple[Topic, callable]] = {
    "clinical": (clinical.TOPIC, clinical.generate),
    "supermarket": (supermarket.TOPIC, supermarket.generate),
    "finance": (finance.TOPIC, finance.generate),
    "automobile": (automobile.TOPIC, automobile.generate),
    "education": (education.TOPIC, education.generate),
}

#: Formats this script knows how to produce. pdf/png/jpeg are generated by
#: separate renderer modules and are added here as they land.
DATA_FORMATS = ["csv", "json", "db", "schemas"]

#: Format directories that get a generated README.md. "schemas" is excluded
#: because it is a machine-readable directory, not one people browse.
DOCUMENTED_FORMATS = ["csv", "json", "db", "pdf", "png", "jpeg"]


def human_size(byte_count: int) -> str:
    """Format a byte count the way a person would read it."""
    size = float(byte_count)
    for unit in ("B", "KB", "MB", "GB"):
        if size < 1024 or unit == "GB":
            return f"{size:,.0f} {unit}" if unit == "B" else f"{size:,.1f} {unit}"
        size /= 1024
    return f"{size:,.1f} GB"



def prune_orphans(
    topic_name: str, formats: list[str], written: list[Path], erd_written: bool
) -> list[Path]:
    """Delete files in this topic's folders that the build did not just write.

    WHY THIS EXISTS: the build used to be purely additive. Rename a table,
    or change a policy about which tables get an .ndjson, and the old file
    stayed on disk forever -- and, worse, the generated folder README went
    on advertising it as though it were current data.

    It was invisible because rebuilding over an existing tree reproduced
    itself perfectly; only a build from an empty directory revealed that the
    committed tree contained files nothing produced.

    Only the formats actually being built are pruned. `--format csv` must
    not delete the JSON.
    """
    current = {path.resolve() for path in written}

    # Which directories this run is responsible for.
    directories: list[Path] = []
    for fmt in formats:
        directories.append(REPO_ROOT / fmt / topic_name)
    if erd_written:
        directories.append(REPO_ROOT / "png" / topic_name)

    removed: list[Path] = []
    for directory in directories:
        if not directory.is_dir():
            continue
        for path in sorted(directory.iterdir()):
            if path.is_file() and path.resolve() not in current:
                path.unlink()
                removed.append(path)

    return removed


def build_topic(name: str, formats: list[str], scale: float) -> list[Path]:
    """Generate one topic's rows and write them out in the requested formats.

    Returns the list of files written, so the caller can report on them.
    """
    topic, generate = TOPICS[name]

    print(f"\n\033[1m{topic.title}\033[0m  ({name})")
    print(f"  {topic.summary}")

    started = time.perf_counter()
    tables = generate(scale=scale)
    elapsed = time.perf_counter() - started

    total_rows = sum(len(rows) for rows in tables.values())
    print(f"  generated {total_rows:,} rows across {len(tables)} tables "
          f"in {elapsed:.1f}s")

    written: list[Path] = []

    # The biggest table gets the NDJSON treatment -- see below.
    largest_table = max(tables, key=lambda name: len(tables[name]))

    # Write in dependency order -- parents before children -- so that the
    # SQLite foreign keys can be enforced as we insert.
    ordered = topic.build_order()

    for entity in ordered:
        rows = tables[entity.name]

        if "csv" in formats:
            written.append(write_csv(entity, rows, REPO_ROOT))
        if "json" in formats:
            written.append(write_json(entity, rows, REPO_ROOT))
            # NDJSON for ONE representative table per topic -- the largest
            # one. It is a streaming-format sample, not a second copy of the
            # whole dataset: generating it for every table roughly doubled
            # the size of json/ for no extra teaching value.
            if entity.name == largest_table:
                written.append(write_ndjson(entity, rows, REPO_ROOT))
        if "schemas" in formats:
            written.append(write_schema(entity, REPO_ROOT))

    if "db" in formats:
        ordered_tables = [(entity, tables[entity.name]) for entity in ordered]
        written.append(write_sqlite(name, ordered_tables, REPO_ROOT))
        written.append(write_schema_sql(name, ordered_tables, REPO_ROOT))
        written.append(write_sql_dump(name, ordered_tables, REPO_ROOT))

    # The ERD is drawn before the docs, so that the folder README for png/
    # can list the image that was just produced.
    row_counts = {entity: len(rows) for entity, rows in tables.items()}
    erd_path = render_erd(topic, row_counts, REPO_ROOT)
    if erd_path is not None:
        written.append(erd_path)
        written.append(erd_path.with_suffix(".dot"))

    # Documentation is generated LAST, because it reports the size and row
    # count of the files that were just written.
    docs_written = write_topic_docs(topic, row_counts, DOCUMENTED_FORMATS, REPO_ROOT)
    written.extend(docs_written)

    for entity in ordered:
        row_count = len(tables[entity.name])
        csv_path = REPO_ROOT / "csv" / name / f"{entity.name}.csv"
        size = human_size(csv_path.stat().st_size) if csv_path.exists() else "-"
        print(f"    {entity.name:<22} {row_count:>8,} rows   {size:>10}")

    # Remove anything left over from a previous shape of this topic.
    removed = prune_orphans(name, formats, written, erd_path is not None)
    if removed:
        print(f"    {'pruned':<22} {len(removed):>8,} orphaned file(s)")
        for path in removed[:5]:
            print(f"        {path.relative_to(REPO_ROOT)}")

    print(f"    {'docs':<22} {len(docs_written):>8,} pages")
    if erd_path is None:
        print("    erd                    skipped -- Graphviz 'dot' not found "
              "(sudo apt install graphviz)")
    else:
        print(f"    {'erd':<22} {'png/' + name + '/erd.png':>26}")
    return written


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="build.py",
        description="Regenerate the realistic-test-data files.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__.split("COMMON TASKS")[1] if "COMMON TASKS" in __doc__ else None,
    )
    parser.add_argument(
        "--topic",
        help="Topic to build (default: all of them). "
             f"Available: {', '.join(sorted(TOPICS))}",
    )
    parser.add_argument(
        "--format",
        default=",".join(DATA_FORMATS),
        help=f"Comma-separated formats to write. Default: all "
             f"({', '.join(DATA_FORMATS)})",
    )
    parser.add_argument(
        "--scale",
        type=float,
        default=1.0,
        help="Multiplier on the default row counts. --scale 10 gives ten "
             "times as many rows. Default: 1.0",
    )
    parser.add_argument(
        "--all", action="store_true",
        help="Build every topic. Same as omitting --topic.",
    )
    parser.add_argument(
        "--list", action="store_true",
        help="List the available topics and their tables, then exit.",
    )
    args = parser.parse_args()

    if args.list:
        for name, (topic, _) in sorted(TOPICS.items()):
            print(f"\n\033[1m{name}\033[0m -- {topic.title}")
            print(f"  {topic.summary}")
            for entity in topic.build_order():
                print(f"    {entity.name:<22} {entity.grain}")
        print()
        return 0

    if args.topic and args.topic not in TOPICS:
        print(f"error: unknown topic {args.topic!r}. "
              f"Available: {', '.join(sorted(TOPICS))}", file=sys.stderr)
        return 2

    formats = [part.strip() for part in args.format.split(",") if part.strip()]
    unknown = [part for part in formats if part not in DATA_FORMATS]
    if unknown:
        print(f"error: unknown format(s) {', '.join(unknown)}. "
              f"Available: {', '.join(DATA_FORMATS)}", file=sys.stderr)
        return 2

    selected = [args.topic] if args.topic else sorted(TOPICS)

    print(f"Building {len(selected)} topic(s): {', '.join(selected)}")
    print(f"Formats: {', '.join(formats)}")
    if args.scale != 1.0:
        print(f"Scale: {args.scale}x")

    started = time.perf_counter()
    all_written: list[Path] = []
    for name in selected:
        all_written.extend(build_topic(name, formats, args.scale))

    all_written.extend(
        write_format_indexes(
            [TOPICS[name][0] for name in sorted(TOPICS)],
            DOCUMENTED_FORMATS,
            REPO_ROOT,
        )
    )
    elapsed = time.perf_counter() - started

    total_bytes = sum(path.stat().st_size for path in all_written if path.exists())
    print(f"\n\033[1m✓ {len(all_written)} files, {human_size(total_bytes)}, "
          f"{elapsed:.1f}s\033[0m")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
